### ISSUE TITLE
Build failure in Objective C++ projects [BUG]

### ISSUE THREAD

**Issue by diegomichell** [Azure/azure-notificationhubs-ios#136]
**Describe the bug**
Some of the files like MSNotificationHub.m and MSNotificationHub.h use "template" as the name for properties which is a reserved keyword in Objective C++, this essentially prevents projects that use Objective C++ from calling this library and this also affects React Native users as the latest version of the framework uses Objective C++ for the AppDelegate.mm 

***Exception or Stack Trace***
Expected identifier; 'template' is a keyword in Objective-C++

**To Reproduce**
Reference the library in .mm files.

***Code Snippet***
`+ (BOOL)setTemplate:(MSInstallationTemplate *)template forKey:(NSString *)key {
    return [sharedInstance setTemplate:template forKey:key];
}`

this and other similar code where "template" keyword is used.

**Expected behavior**
The project should compile without errors.

**Setup (please complete the following information):**
 - OS: 16.2
 - IDE : 14.2
 - Version of the Library used: 3.1.5

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by brannon** [comment]
Thanks for pointing this out! I have a [PR](https://github.com/Azure/azure-notificationhubs-ios/pull/138) that should resolve this. I'll get it merged once it passes the required checks.

**Comment by brannon** [comment]
This should be fixed in #138

**Comment by diegomichell** [comment]
This was fixed, though do you know when a new binary will be created and available for installation through cocoa pods that include this change?

**Comment by mrzslr** [comment]
hey, this issue still exists. even downloading the latest release source codes and still using `template` keyword instead of `installationTemplate`

**Comment by brannon** [comment]
@marstr this issue was fixed a while back, but it requires a new release of the SDK.

I'll reopen the issue for now. We can close it once the fix is released.

**Comment by marstr** [comment]
Acknowledged. Thanks for bringing this back to our attention, @brannon.

**Comment by hieucm** [comment]
Can we know when this fixed is released?

**Comment by Brqqq** [comment]
Are there any plans for a release @marstr ?

**Comment by marstr** [comment]
Howdy - I accepted a new role, and the team transitioned to new ownership in a different department. I'll see if I can get this thread some attention from the new owners. But I'm afraid I won't be of much more help than that.

**Comment by anthony-7** [comment]
I've just added AzureNotificationHubs-iOS using cocoa pods. Podfile.lock is showing me that 3.1.5 is installed. I'm getting these template errors in MSInstallation.h and MSNotificationHub.h. I can see in your repository that your files were updated 2 years ago. What do I need to do to get the updated files ?
