### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by johnmartino** [Azure/azure-notificationhubs-ios#150]
**Describe the bug**
The framework doesn't compile under Xcode 16.

***Exception or Stack Trace***
The error is:
'ANHAsync.h' file not found

**To Reproduce**
Add the package in a project and try to build in Xcode 16.

***Code Snippet***
No application specific code required.

**Expected behavior**
The framework should build.

**Screenshots**

**Setup (please complete the following information):**
 - OS: iOS 16+
 - IDE : Xcode 16
 - 3.1.5

**Additional context**
Nothing to add.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by shvetsjr** [comment]
Having same issue with using xcode 16 too

**Comment by shvetsjr** [comment]
@johnmartino I cloned the repo for now and made few changes and it seem to work.

Firstly I removed `ANHAsync.h` file and replaced `ANH_SWIFT_DISABLE_ASYNC` with `NS_SWIFT_DISABLE_ASYNC`
and secondly I had to fix few imports but not sure its the correct way to do it but it worked..  

```
-#import "SBTemplateRegistration.h"
+#import "../SBTemplateRegistration.h"
```

Hope for official fix

**Comment by johnmartino** [comment]
Thanks @shvetsjr.  I will try your solution, or maybe just add the framework itself.   I know that there won't be a fix before Xcode 16 is officially released in a few months.  I was hoping that this would be fixed beforehand since I really dislike not upgrading when it's time.

**Comment by johnmartino** [comment]
It seems that Xcode 16 beta 4 fixes this issue.

**Comment by learnwithgabbar** [comment]
Not Fixed in  Xcode 16 beta 4 SPM way

**Comment by newky2k** [comment]
This was an issue in Xcode 15 beta too, but resolved itself by the final release - #145 

I would be good if this could be resolved, as above, as it will make it easier to test out new Xcode betas before they launch and this is the only SPM package we use that fails.

**Comment by learnwithgabbar** [comment]
Still in the Xcode 16 RC

**Comment by newky2k** [comment]
@IonDrumea Do you think the changes you did on your fork could be PR'd back into the main repo and fix this issue moving forward so we don't all get this everytime Apple releases a beta?

**Comment by nharbo** [comment]
It's not even only in the beta - the GM version gives this error as well.

**Comment by johnmartino** [comment]
I was informed that there will be a fix for this but it may not happen for several weeks or even months.  It's a resource issue but they are trying to rectify the issue.  I know that's not a satisfying answer.  For now, I'm directly including the framework.

**Comment by newky2k** [comment]
Just tested this morning and 16.1 still gives the same error

**Comment by nharbo** [comment]
There's a workaround here: https://github.com/Azure/azure-notificationhubs-ios/issues/153#issuecomment-2381300188

**Comment by ljunquera** [comment]
It does not look like this has been resolved yet and it has been open for a while. Is there a timeline to resolution?

**Comment by PeterStaev** [comment]
Amazing that after almost 2 years this is not yet resolved. Pods are becoming obsolete in a month or so, so anyone using SPM will hit this problem. Even using the latest non-beta XCode the problem exists. Can we have an official solution?

**Comment by johnmartino** [comment]
I created a PR to fix this but they don’t seem interested in fixing it.
